/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gd_hotel.QLKS;

import com.hotel.dao.ChiTietHoaDonDAO;
import com.hotel.dao.HoaDonDAO;
import com.hotel.database.DatabaseConnection;
import com.hotel.model.ChiTietHoaDon;
import com.hotel.model.HoaDon;
import gd_hotel.MANAGER_PAGE;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Date;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.JPopupMenu;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author HOANG PHI
 */
public class HoaDon_Form extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(HoaDon_Form.class.getName());

    /**
     * Creates new form HoaDon_Form
     */
    public HoaDon_Form() {
        initComponents();
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        
        try (Connection conn = DatabaseConnection.getConnection()) {
            DefaultTableModel model = (DefaultTableModel) tbShowHD.getModel();
            HoaDonDAO hdd = new HoaDonDAO();
            List <HoaDon> HD = hdd.getAll();
            for(HoaDon hd : HD){
                model.addRow(new Object[] {
                    hd.getMaHD(),
                    sdf.format(hd.getNgayLap()),
                    hd.getMaNV(),
                    hd.getMaDP()
                });
            }
            
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Lỗi khi tải dữ liệu: " + ex.getMessage());
        }
        setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                // Ẩn cửa sổ hiện tại
                HoaDon_Form.this.setVisible(false);

                // Mở MANAGER_PAGE
                java.awt.EventQueue.invokeLater(() -> new MANAGER_PAGE().setVisible(true));
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbShowHD = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbShowCTHD = new javax.swing.JTable();
        btnAdd1 = new javax.swing.JButton();
        btnUpdate1 = new javax.swing.JButton();
        btnDelete1 = new javax.swing.JButton();
        btnFind1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbAdd = new javax.swing.JTable();
        btnChon = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tbShowHD.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã HĐ", "Ngày Lập", "Mã NV", "Mã DP"
            }
        ));
        tbShowHD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbShowHDMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbShowHD);

        tbShowCTHD.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã HĐ", "STT", "Nội Dung", "Số Lượng", "Đơn Giá"
            }
        ));
        tbShowCTHD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbShowCTHDMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbShowCTHD);

        btnAdd1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48-free-object-icons/png/48x48/Add.png"))); // NOI18N
        btnAdd1.setText("Thêm");
        btnAdd1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdd1ActionPerformed(evt);
            }
        });

        btnUpdate1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48-free-object-icons/png/48x48/edit-icon.png"))); // NOI18N
        btnUpdate1.setText("Sửa");
        btnUpdate1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdate1ActionPerformed(evt);
            }
        });

        btnDelete1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48-free-object-icons/png/48x48/Minus.png"))); // NOI18N
        btnDelete1.setText("Xóa");
        btnDelete1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelete1ActionPerformed(evt);
            }
        });

        btnFind1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48-free-object-icons/png/48x48/Search.png"))); // NOI18N
        btnFind1.setText("Tìm");
        btnFind1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFind1ActionPerformed(evt);
            }
        });

        jPanel1.setLayout(null);

        tbAdd.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tbAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbAddMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tbAdd);

        btnChon.setText("Chọn");
        btnChon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 485, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 703, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(btnChon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 1039, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAdd1)
                .addGap(86, 86, 86)
                .addComponent(btnUpdate1)
                .addGap(86, 86, 86)
                .addComponent(btnDelete1)
                .addGap(86, 86, 86)
                .addComponent(btnFind1)
                .addGap(250, 250, 250))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 426, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnChon)
                        .addGap(54, 54, 54)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdd1)
                    .addComponent(btnUpdate1)
                    .addComponent(btnDelete1)
                    .addComponent(btnFind1))
                .addContainerGap(52, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    int check = 0;
    
    private void loadEmptyTable(int selected) {
        DefaultTableModel model = (DefaultTableModel) tbAdd.getModel();
        model.setRowCount(0); // Xóa bảng cũ

        switch (selected) {
            case 1 -> {
                model.setColumnIdentifiers(new String[]{"Mã HD", "Ngày Lập", "Mã NV", "Mã DP"});
                check = 1;
            }
            case 2 -> {
                model.setColumnIdentifiers(new String[]{"Mã HD", "STT", "Nội Dung", "Số Lượng", "Đơn Giá"});
                check = 2;
            }
        }

        // Thêm 1 dòng trống để nhập dữ liệu
        model.addRow(new Object[model.getColumnCount()]);
    }

    private void loadChiTietHoaDon(String maHD) {
        ChiTietHoaDonDAO dao = new ChiTietHoaDonDAO();
        List<ChiTietHoaDon> list = dao.getByMaHD(maHD);

        DefaultTableModel model = (DefaultTableModel) tbShowCTHD.getModel();
        model.setRowCount(0);

        for (ChiTietHoaDon ct : list) {
            model.addRow(new Object[]{
                ct.getMaHD(),
                ct.getSoThuTu(),
                ct.getNoiDung(),
                ct.getSoLuong(),
                ct.getDonGia()
            });
        }
    }
    

    
    private void tbShowHDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbShowHDMouseClicked
        // TODO add your handling code here:        
        DefaultTableModel modelUpdate = (DefaultTableModel) tbAdd.getModel();
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        int row = tbShowHD.getSelectedRow();
        if (row >= 0) {
            String maHD = tbShowHD.getValueAt(row, 0).toString();
            loadChiTietHoaDon(maHD);
            
            modelUpdate.setRowCount(0);
            HoaDonDAO dao = new HoaDonDAO();
            List<HoaDon> list = new ArrayList<>();
            list.add(dao.findById(maHD));

            for (HoaDon hd : list) {
                modelUpdate.addRow(new Object[]{
                    hd.getMaHD(),
                    sdf.format(hd.getNgayLap()),
                    hd.getMaNV(),
                    hd.getMaDP()
                });
            }
        }    
    }//GEN-LAST:event_tbShowHDMouseClicked

    
    private void btnAdd1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdd1ActionPerformed
        HoaDonDAO HDD = new HoaDonDAO();
        ChiTietHoaDonDAO CTHDD = new ChiTietHoaDonDAO();

        DefaultTableModel modelAdd = (DefaultTableModel) tbAdd.getModel();
        DefaultTableModel modelShowHD = (DefaultTableModel) tbShowHD.getModel();
        DefaultTableModel modelShowCTHD = (DefaultTableModel) tbShowCTHD.getModel();

        switch(check){
            case 1 -> {
                String maHD = modelAdd.getValueAt(0, 0).toString();
                String ngayLapStr = modelAdd.getValueAt(0, 1).toString().trim();
                String maNV = modelAdd.getValueAt(0, 2).toString();
                String maDP = modelAdd.getValueAt(0, 3).toString();

                Date ngayLap = Date.valueOf(ngayLapStr);

                modelShowHD.addRow(new Object[]{
                    maHD,
                    ngayLapStr,
                    maNV,
                    maDP
                });

                HoaDon HD = new HoaDon();
                HD.setMaHD(maHD);
                HD.setNgayLap(ngayLap);
                HD.setMaNV(maNV);
                HD.setMaDP(maDP);

                if (HDD.insert(HD)) {
                    JOptionPane.showMessageDialog(this, "Thêm thành công!");
                } else {
                    JOptionPane.showMessageDialog(this, "Lỗi khi thêm!");
                }
            }
            case 2 -> {
                String maHD = modelAdd.getValueAt(0, 0).toString();
                String stt = modelAdd.getValueAt(0, 1).toString();
                String noiDung = modelAdd.getValueAt(0, 2).toString();
                String soLuong = modelAdd.getValueAt(0, 3).toString();
                String donGia = modelAdd.getValueAt(0, 4).toString();

                modelShowCTHD.addRow(new Object[]{
                    maHD,stt,noiDung,soLuong,donGia});

                ChiTietHoaDon CTHD = new ChiTietHoaDon(maHD,Integer.parseInt(stt),noiDung,Integer.parseInt(soLuong),Double.parseDouble(donGia));
                
                if (CTHDD.insert(CTHD)) {
                    JOptionPane.showMessageDialog(this, "Thêm thành công!");
                } else {
                    JOptionPane.showMessageDialog(this, "Lỗi khi thêm!");
                }
            }
        }


    }//GEN-LAST:event_btnAdd1ActionPerformed

    private void btnUpdate1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdate1ActionPerformed
        int row = tbShowHD.getSelectedRow();
        HoaDonDAO HDD = new HoaDonDAO();
        ChiTietHoaDonDAO CTHDD = new ChiTietHoaDonDAO();

        DefaultTableModel modelAdd = (DefaultTableModel) tbAdd.getModel();
        DefaultTableModel modelShowHD = (DefaultTableModel) tbShowHD.getModel();
        DefaultTableModel modelShowCTHD = (DefaultTableModel) tbShowCTHD.getModel();
        
        switch(check){
            case 1 -> {
                if (row < 0) {
                    JOptionPane.showMessageDialog(this, "Vui lòng chọn 1 hàng để sửa.");
                    return;
                }

                String maHD = modelAdd.getValueAt(0, 0).toString();
                String ngayLapStr = modelAdd.getValueAt(0, 1).toString();
                Date ngayLap = Date.valueOf(ngayLapStr); 
                String maNV = modelAdd.getValueAt(0, 2).toString();
                String maDP = modelAdd.getValueAt(0, 3).toString();

                modelShowHD.setValueAt(maHD, row, 0);
                modelShowHD.setValueAt(ngayLapStr, row, 1);
                modelShowHD.setValueAt(maNV, row, 2);
                modelShowHD.setValueAt(maDP, row, 3);

                HoaDon hd = new HoaDon(maHD, ngayLap, maNV, maDP);

                if (HDD.update(hd)) {
                    JOptionPane.showMessageDialog(this, "Cập nhật thành công!");
                } else {
                    JOptionPane.showMessageDialog(this, "Lỗi khi cập nhật!");
                }
            }
            case 2 -> {
                if (row < 0) {
                    JOptionPane.showMessageDialog(this, "Vui lòng chọn 1 hàng để sửa.");
                    return;
                }

                String maHD = modelAdd.getValueAt(0, 0).toString();
                String stt = modelAdd.getValueAt(0, 1).toString();
                String noiDung = modelAdd.getValueAt(0, 2).toString();
                String soLuong = modelAdd.getValueAt(0, 3).toString();
                String donGia = modelAdd.getValueAt(0, 4).toString();

                modelShowCTHD.setValueAt(maHD, row, 0);
                modelShowCTHD.setValueAt(stt, row, 1);
                modelShowCTHD.setValueAt(noiDung, row, 2);
                modelShowCTHD.setValueAt(soLuong, row, 3);
                modelShowCTHD.setValueAt(donGia, row, 4);

                ChiTietHoaDon CTHD = new ChiTietHoaDon(maHD,Integer.parseInt(stt),noiDung,Integer.parseInt(soLuong),Double.parseDouble(donGia));

                if (CTHDD.update(CTHD)) {
                    JOptionPane.showMessageDialog(this, "Cập nhật thành công!");
                } else {
                    JOptionPane.showMessageDialog(this, "Lỗi khi cập nhật!");
                }
            }
        }
        

    }//GEN-LAST:event_btnUpdate1ActionPerformed

    private void btnDelete1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelete1ActionPerformed
        
        switch(check){
            case 1 -> {
                int row = tbShowHD.getSelectedRow();

                if (row < 0) {
                    JOptionPane.showMessageDialog(this, "Bạn phải chọn dòng để xóa!");
                    return;
                }

                String maHD = tbShowHD.getValueAt(row, 0).toString();

                HoaDonDAO dao = new HoaDonDAO();

                if (dao.delete(maHD)) {
                    JOptionPane.showMessageDialog(this, "Xóa thành công!");
                    DefaultTableModel model = (DefaultTableModel) tbShowHD.getModel();
                    model.removeRow(row);
                } else {
                    JOptionPane.showMessageDialog(this, "Xóa thất bại!");
                }
            }
            
            case 2 -> {
                int row = tbShowCTHD.getSelectedRow();

                if (row < 0) {
                    JOptionPane.showMessageDialog(this, "Bạn phải chọn dòng để xóa!");
                    return;
                }

                String maHD = tbShowCTHD.getValueAt(row, 0).toString();
                String stt = tbShowCTHD.getValueAt(row, 1).toString();
                
                ChiTietHoaDonDAO dao = new ChiTietHoaDonDAO();

                if (dao.delete(maHD, Integer.parseInt(stt))) {
                    JOptionPane.showMessageDialog(this, "Xóa thành công!");
                    DefaultTableModel model = (DefaultTableModel) tbShowCTHD.getModel();
                    model.removeRow(row);
                } else {
                    JOptionPane.showMessageDialog(this, "Xóa thất bại!");
                }
            }
            
            default -> {
                JOptionPane.showMessageDialog(this, "Vui lòng chọn bảng muốn xóa!");
            }
        }
        
    }//GEN-LAST:event_btnDelete1ActionPerformed

    private void btnFind1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFind1ActionPerformed
        String maHD = JOptionPane.showInputDialog("Nhập mã hóa đơn:");

        HoaDonDAO dao = new HoaDonDAO();
        HoaDon hd = dao.findById(maHD);

        DefaultTableModel model = (DefaultTableModel) tbAdd.getModel();
        model.setRowCount(0);

        if (hd != null) {
            model.addRow(new Object[]{
                hd.getMaHD(),
                hd.getNgayLap(),
                hd.getMaNV(),
                hd.getMaDP()
            });
        } else {
            JOptionPane.showMessageDialog(this, "Không tìm thấy!");
        }
    }//GEN-LAST:event_btnFind1ActionPerformed

    private void tbAddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbAddMouseClicked
    
        int row = tbAdd.getSelectedRow();
        if (row >= 0) {
            String maHD = tbAdd.getValueAt(row, 0).toString();
            loadChiTietHoaDon(maHD);
            
        }
    }//GEN-LAST:event_tbAddMouseClicked

    private void btnChonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChonActionPerformed
        JPopupMenu pop = new JPopupMenu();

        JMenuItem m1 = new JMenuItem("Bảng 1: Hóa Đơn");
        JMenuItem m2 = new JMenuItem("Bảng 2: Chi Tiết Hóa Đơn");

        // Gắn các sự kiện chọn bảng
        m1.addActionListener(e -> loadEmptyTable(1));
        m2.addActionListener(e -> loadEmptyTable(2));

        pop.add(m1);
        pop.add(m2);

        // Hiện popup ngay dưới nút bấm
        pop.show(btnChon, 0, btnChon.getHeight());
    }//GEN-LAST:event_btnChonActionPerformed

    private void tbShowCTHDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbShowCTHDMouseClicked
        DefaultTableModel modelUpdate = (DefaultTableModel) tbAdd.getModel();
        
        int row = tbShowCTHD.getSelectedRow();
        if (row >= 0) {
            String maHD = tbShowCTHD.getValueAt(row, 0).toString();
            loadChiTietHoaDon(maHD);
            
            modelUpdate.setRowCount(0);
            modelUpdate.addRow(new Object[]{
                tbShowCTHD.getValueAt(row, 0),
                tbShowCTHD.getValueAt(row, 1),
                tbShowCTHD.getValueAt(row, 2),
                tbShowCTHD.getValueAt(row, 3),
                tbShowCTHD.getValueAt(row, 4)
            });
        }
         
    }//GEN-LAST:event_tbShowCTHDMouseClicked

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new HoaDon_Form().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd1;
    private javax.swing.JButton btnChon;
    private javax.swing.JButton btnDelete1;
    private javax.swing.JButton btnFind1;
    private javax.swing.JButton btnUpdate1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tbAdd;
    private javax.swing.JTable tbShowCTHD;
    private javax.swing.JTable tbShowHD;
    // End of variables declaration//GEN-END:variables

}
